# Generated by Django 5.0.6 on 2024-07-06 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('ba941f23-1e7e-4a78-8e1f-8ae58faa2cb6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('d398f755-10bc-4e4d-83b2-fd1243ffd0ca'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
