# Generated by Django 5.0.6 on 2024-07-06 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_attendingcourse_attending_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('61cfa984-9222-418d-9814-0aad8fb3bc92'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('c121ed19-fb09-4e60-8994-99f6c629831a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
