# Generated by Django 5.0.6 on 2024-07-06 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_attendingcourse_attending_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('5798325f-3d0b-4d4d-ae57-fdc82b59fbab'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('bccbf9c5-a2ef-4a1f-9baf-642e70c09879'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
