# Generated by Django 5.0.4 on 2024-07-07 06:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_attendingcourse_attending_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('cfa90cc7-f68b-46b3-ada6-af54b5334807'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('7dc5c487-6fbf-4e89-804e-fe0be77fa0c6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
