# Generated by Django 5.0.6 on 2024-07-06 16:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_attendingcourse_attending_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('d7b8975d-c407-45bd-9cd3-d74ee7513c91'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('8cb6ab5c-6150-4e6b-a01d-475237f8f98a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
