# Generated by Django 5.0.4 on 2024-07-07 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_attendingcourse_attending_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('4635a8b1-5c19-4407-a1e4-9d131120d3c2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('fce7cd1e-5769-462e-aa61-45bd1ca15843'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
