# Generated by Django 5.0.4 on 2024-07-07 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_attendingcourse_attending_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('a074626f-a11d-4732-a11c-68c9908d0039'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('3b58f4a6-3f1b-4a68-8eff-9553292f93b9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
