# Generated by Django 5.0.6 on 2024-07-15 02:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_attendingcourse_attending_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('0b4323d6-4a49-4722-97e6-ee9b2e02c897'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('18db4aae-6bc4-4441-acf0-d9559dc799a6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
