# Generated by Django 5.0.6 on 2024-06-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountuser',
            new_name='apps1_accou_account_e66dc4_idx',
            old_name='apps1_accou_account_d092da_idx',
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_related_user',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
